### ISSUE TITLE
Running cli locally results in Mogrify IO error?

### ISSUE THREAD

**Issue by gabriellet** [bunnymatic/slack_color_theme_generator#12]
I've been trying to get this running locally on my machine for a bit without much success. After uncommenting the `escript` function in `mix.exs` and commenting out the `application` function, I was able to get it to run, but I promptly ran into this Erlang error that seems to be related to file IO. This is the stack trace I get.

```
Gabrielles-MacBook-Air:slack_color_theme_generator Gabrielle$ mix escript.build
Compiling 1 file (.ex)
warning: defp inspector/2 is private, @doc attribute is always discarded for private functions/macros/types
  lib/slack_color_theme_generator.ex:6

Generated escript slack_color_theme_generator with MIX_ENV=dev
Gabrielles-MacBook-Air:slack_color_theme_generator Gabrielle$ ./slack_color_theme_generator ./clouds.jpg

13:13:27.034 [info]  Generating for ./clouds.jpg

13:13:27.035 [info]  Computing histogram from ./clouds.jpg
** (ErlangError) Erlang error: :enoent
    (elixir) lib/system.ex:622: System.cmd("convert", ["-background", "white", "-alpha", "remove", "-colors", "8", "+dither", "-format", "%c", "/Users/Gabrielle/workspace/slack_color_theme_generator/clouds.jpg", "histogram:info:-"], [stderr_to_stdout: false])
    (mogrify) lib/mogrify.ex:68: Mogrify.histogram/1
    (slack_color_theme_generator) lib/slack_color_theme_generator.ex:125: SlackColorThemeGenerator.histogram/1
    (slack_color_theme_generator) lib/slack_color_theme_generator.ex:31: SlackColorThemeGenerator.generate/2
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    (slack_color_theme_generator) lib/slack_color_theme_generator/cli.ex:4: SlackColorThemeGenerator.CLI.main/1
    (elixir) lib/kernel/cli.ex:105: anonymous fn/3 in Kernel.CLI.exec_fun/2
Gabrielles-MacBook-Air:slack_color_theme_generator Gabrielle$ 
```

I also tried some debugging by adding this to the histogram function: 
```
image = Mogrify.open(file)
Logger.info( fn -> "Image is #{Mogrify.verbose(image)}" end)
```
which resulted in a similar stack trace. 
``` 
Gabrielles-MacBook-Air:slack_color_theme_generator Gabrielle$ ./slack_color_theme_generator ./clouds.jpg

13:15:34.197 [info]  Generating for ./clouds.jpg

13:15:34.199 [info]  Computing histogram from ./clouds.jpg
** (ErlangError) Erlang error: :enoent
    (elixir) lib/system.ex:622: System.cmd("mogrify", ["-verbose", "-write", "/dev/null", "/Users/Gabrielle/workspace/slack_color_theme_generator/clouds.jpg"], [stderr_to_stdout: true])
    (mogrify) lib/mogrify.ex:165: Mogrify.verbose/1
    (slack_color_theme_generator) lib/slack_color_theme_generator.ex:119: anonymous fn/1 in SlackColorThemeGenerator.histogram/1
    (logger) lib/logger.ex:758: Logger.normalize_message/2
    (logger) lib/logger.ex:618: Logger.bare_log/3
    (slack_color_theme_generator) lib/slack_color_theme_generator.ex:119: SlackColorThemeGenerator.histogram/1
    (slack_color_theme_generator) lib/slack_color_theme_generator.ex:31: SlackColorThemeGenerator.generate/2
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
Gabrielles-MacBook-Air:slack_color_theme_generator Gabrielle$ 
```

 Any thoughts?

**Comment by bunnymatic** [comment]
Yup.

1) you need ImageMagick on your machine.  Try, in a terminal `which identify` or `which mogrify`?  I suspect it will give you nothing.   You can install image magick via brew `brew install imagemagick`.

2) the CLI thing is a real problem.  I need to learn more elixir to figure out how to set up the config so that you can *either* run a CLI or run the slack client.  Right now, as you figured out, you need to comment out the slackbot hookup to run it as an escript.  

Try installing imagemagick and see if that gets you further.    We could do a little pairing too cuz if you figured out how to swap between cli/escript and slackbot, i'd love it.

**Comment by gabriellet** [comment]
Turns out installing the right dependencies is helpful. Thanks!

**Comment by bunnymatic** [comment]
i suppose someone (i) should add that to the readme.
